version: '3.8'

services:

  db:
    image: postgres:14
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - "80:80" 
    networks:
      - backend
    depends_on:
      - db 

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
